#!/usr/bin/env sh

function pause(){
   read -p "$*"
}

CURRENT=`dirname $0`

function link_to_home(){
    NAME="$1"
    SOURCE="$CURRENT/$NAME"
    TARGET="$HOME/$2"
    if [[ -e "$SOURCE" ]]; then

        if [[ -e "$TARGET/$NAME" ]]; then
            echo "\"$TARGET/$NAME\" aleady exist"
        else
            echo "\"$SOURCE\" -> \"$TARGET\""
            ln -s "$SOURCE" "$TARGET"  
        fi
    else
        echo "$SOURCE not exist, please check"  
    fi
}

link_to_home "Sublime Text 3"       "Library/Application Support"
link_to_home "Eudb_en"              "Library"
link_to_home "WebStorm2016.1"       "Preferences"

pause 'Press [Enter] key to continue...'
